// Generated by CoffeeScript 1.12.5
(function() {
  angular.module('app').factory('cache', [
    function() {
      var services;
      services = {
        set: function(key, value) {
          var data;
          data = JSON.stringify(value);
          return window.localStorage.setItem(key, data);
        },
        get: function(key) {
          var data;
          data = window.localStorage.getItem(key);
          return JSON.parse(data);
        }
      };
      return services;
    }
  ]);

}).call(this);

//# sourceMappingURL=cache.js.map
