// Generated by CoffeeScript 1.12.5
(function() {
  var has_jquery, inject_script;

  has_jquery = function() {
    var $;
    $ = window.jQuery;
    if ($ && $.fn && $.fn.jquery) {
      return true;
    }
    return false;
  };

  inject_script = function(script, onload) {
    var s;
    s = document.createElement('script');
    s.src = chrome.extension.getURL(script);
    (document.head || document.documentElement).appendChild(s);
    return s.onload = function() {
      if (onload) {
        onload();
      }
      return s.parentNode.removeChild(s);
    };
  };

}).call(this);

//# sourceMappingURL=content_script.js.map
