// Generated by CoffeeScript 1.12.5
(function() {
  var $container, $iframe, $toolbar, logger, panel_url, request_context_search, root_url, send_message_to_panel;

  $container = $('<div class="unisearch-panel hidden"></div>');

  $toolbar = $("<div class='panel-toolbar'><div class='header'></div><div class='close-btn'></div></div>");

  $toolbar.appendTo($container);

  root_url = chrome.extension.getURL('/');

  root_url = root_url.substring(0, root_url.length - 1);

  panel_url = root_url + '/index.html';

  $iframe = $("<iframe src='" + panel_url + "'>");

  $iframe.appendTo($container);

  $container.appendTo(document.body);

  logger = window.logger;

  send_message_to_panel = function(msg) {
    return $iframe[0].contentWindow.postMessage(msg, '*');
  };

  $(document).on('keydown', function(e) {
    if (e.keyCode === 192 && !e.shiftKey && !e.ctrlKey && !e.metaKey) {
      e.preventDefault();
      e.stopPropagation();
      $container.toggleClass('hidden');
      if ($container.hasClass('hidden')) {
        return window.focus();
      } else {
        return send_message_to_panel({
          'action': 'focus-input'
        });
      }
    }
  });

  $toolbar.find('.close-btn').on('click', function() {
    $container.addClass('hidden');
    return window.focus();
  });

  window.onmessage = function(e) {
    var msg;
    if (e.origin !== root_url) {
      return;
    }
    msg = e.data;
    logger.log('Message↑', '#4CAF50', msg);
    if (msg.action === 'hide-iframe') {
      $container.addClass('hidden');
      return window.focus();
    } else if (msg.action === 'request-parent-info') {
      return send_message_to_panel({
        action: 'response-parent-info',
        require_https: window.location.protocol === 'https:'
      });
    }
  };

  request_context_search = function(keyword) {
    $container.removeClass('hidden');
    return send_message_to_panel({
      action: 'context-search',
      keyword: keyword
    });
  };

  $(document).on('dblclick', function(e) {
    var keyword;
    keyword = window.getSelection().toString().trim();
    if (keyword.length === 0) {
      return;
    }
    return request_context_search(keyword);
  });

  chrome.extension.onMessage.addListener(function(msg, sender, sendResponse) {
    var keyword;
    logger.log('ChromeMessage', '#9C27B0', msg);
    if (msg.action === 'context-search') {
      keyword = msg.keyword;
      return request_context_search(keyword);
    }
  });

}).call(this);

//# sourceMappingURL=inject.js.map
