// Generated by CoffeeScript 1.12.5
(function() {
  var $, debug;

  debug = true;

  $ = window.jQuery;

  $.noConflict();

  if (debug) {
    console.log("Using jQuery " + $.fn.jquery);
  }

  $(document).on('dblclick', function(e) {
    if (debug) {
      return console.log(window.getSelection());
    }
  });

}).call(this);

//# sourceMappingURL=inject_script.js.map
